extends:
  - stylelint-config-standard
  - stylelint-config-rational-order

rules:
  at-rule-empty-line-before: null
  at-rule-no-unknown: null
  declaration-empty-line-before: null
  no-descending-specificity: null
  selector-type-no-unknown: null
  no-duplicate-selectors: null
